name: my_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter

    # Utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  lottie:

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1
  intl_phone_number_input: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/animations/
