// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRD1JoKuYcjsYtzt_Qw-GO5te-jHC88ZU',
    appId: '1:625657751472:web:0bc4c7e96bbd08ea31d875',
    messagingSenderId: '625657751472',
    projectId: 'my-erp-system-69e18',
    authDomain: 'my-erp-system-69e18.firebaseapp.com',
    storageBucket: 'my-erp-system-69e18.appspot.com',
    measurementId: 'G-XSSHQVDKZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAAP_fyPnHhx6AcWr93rpa_aWu4ET9c5g',
    appId: '1:625657751472:android:e931d7ef940121a831d875',
    messagingSenderId: '625657751472',
    projectId: 'my-erp-system-69e18',
    storageBucket: 'my-erp-system-69e18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA43CvLTfwiDhUPYQFt2dofW3feSN3TKYc',
    appId: '1:625657751472:ios:42c805b457bbf7a631d875',
    messagingSenderId: '625657751472',
    projectId: 'my-erp-system-69e18',
    storageBucket: 'my-erp-system-69e18.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA43CvLTfwiDhUPYQFt2dofW3feSN3TKYc',
    appId: '1:625657751472:ios:42c805b457bbf7a631d875',
    messagingSenderId: '625657751472',
    projectId: 'my-erp-system-69e18',
    storageBucket: 'my-erp-system-69e18.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRD1JoKuYcjsYtzt_Qw-GO5te-jHC88ZU',
    appId: '1:625657751472:web:caf00206e48c9e2331d875',
    messagingSenderId: '625657751472',
    projectId: 'my-erp-system-69e18',
    authDomain: 'my-erp-system-69e18.firebaseapp.com',
    storageBucket: 'my-erp-system-69e18.appspot.com',
    measurementId: 'G-FL4TS5M96X',
  );
}
